# Generated by Django 6.0 on 2026-06-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequest',
            name='utr_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
