# Generated by Django 6.0 on 2026-06-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequest',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='withdraw_qr/'),
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
