# Generated by Django 6.0 on 2026-06-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chatroom_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequest',
            name='request_type',
            field=models.CharField(choices=[('ADD', 'Add Fund'), ('WITHDRAW', 'Withdraw Fund'), ('BONUS', 'Bonus')], max_length=20),
        ),
    ]
