# Generated by Django 6.0 on 2026-06-25 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_savedpaymentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedpaymentdetails',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='savedpaymentdetails',
            name='account_name',
            field=models.CharField(default='Primary Account', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedpaymentdetails',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savedpaymentdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
