# Generated by Django 6.0 on 2026-06-25 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_savedpaymentdetails_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequest',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdraw_requests', to='core.savedpaymentdetails'),
        ),
    ]
