# Generated by Django 6.0 on 2026-07-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='reward_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='referral',
            name='reward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
