# Generated by Django 6.0 on 2026-09-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_qrcode_is_active_alter_qrcode_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.IntegerField(unique=True)),
                ('version_name', models.CharField(max_length=20)),
                ('apk', models.FileField(upload_to='apk/')),
                ('force_update', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
